context("Align target sequences")

seqs <- c(
  paste0(
    "AATTTGTCTTATCTCCCTGTACCATTTTGTTGCTATTTTCATTAATAACAGGTAGGATGGTTTTATGGTA",
    "ATATATATGTCACTGATCTGGATCAACTAGGCCACCAACACAAATCTGAATACTGAGAGGA"
  ),
  paste0(
    "CAGAGGGTGCAGAGCGGGAGAGGAAGGACCAGAGCGGGAGGGTAGGAGAGACTCACGCTGGATAGCCTCC",
    "AGGCCAGAAAGAGAGAGTAGCGCGAGCACAGCTAAGGCCACGGAGCGAGACATCTCGGCCC"
  ),
  paste0(
    "GTCTGTCTGCCTATTCACCGATTTTGATTCTCAAACAAATGTGTCACAAAGTAAGGATTCTGATGTGTAT",
    "ATCACAGACAAAACTGTGCTAGACATGAGGTCTATGGACTTCAAGAGCAACAGTGCTGTGG"
  ),
  paste0(
    "GAGCAGCCGCCTGAGGGTCTCGGCCACCTTCTGGCAGAACCCCCGCAACCACTTCCGCTGTCAAGTCCAG",
    "TTCTACGGGCTCTCGGAGAATGACGAGTGGACCCAGGATAGGGCCAAACCCGTCACCCAGA"
  ),
  paste0(
    "GAGCAGCCGCCTGAGGGTCTCGGCCACCTTCTGGCAGAACCCCCGCAACCACTTCCGCTGTCAAGTCCAG",
    "TTCTACGGGCTCTCGGAGAATGACGAGTGGACCCAGGATAGGGCCAAACCTGTCACCCAGA"
  )
)

tar_seqs <- c(
  "B2M" = "GAGTAGCGCGAGCACAGCTA",
  "TRAC" = "TGTGCTAGACATGAGGTCTA",
  "TRBC" = "GGAGAATGACGAGTGGACCC"
)

expected_output <- data.frame(
  "names" = as.character(c(2, 3, 4, 5)),
  "target" = c("B2M", "TRAC", "TRBC", "TRBC"),
  "target.mismatch" = 0,
  "start" = 85L,
  "end" = 104L,
  "width" = 20.0,
  "nt_width" = 131L,
  stringsAsFactors = FALSE
)

test_that(
  desc = "Align targets against queried sequences",
  code = {

    output <- alnTargetSeqs(seqs = seqs, target.seqs = tar_seqs, tolerance = 6L)
    expect_equal(output, expected_output)

  }
)

