#' Write fast(a/q) files given Biostrings and ShortRead objects.
#' 
#' @usage writeSeqFile(seqs, file, compress = FALSE)
#' 
#' @param seqs BioStrings DNAStringSet object generated by trimming from the 
#' pointer object.
#' @param file character Output file name to write sequences.
#' @param compress logical Whether to gzip compress the sequence file when 
#' written or leave it uncompressed. Default is FALSE, or uncompressed.
#' @author Christopher Nobles, Ph.D.

writeSeqFiles <- function(seqs, file, compress = FALSE){
  
  seq_type <- seqFileType(file)
  
  if( seq_type == "fasta" ){
    
    if( compress ){
      
      if( grepl(".gz$", file) ){
        
        ShortRead::writeFasta(
          object = seqs, 
          file = file, 
          compress = TRUE, 
          width = max(c(Biostrings::width(seqs), 1))
        )
        
      }else{
        
        ShortRead::writeFasta(
          object = seqs, 
          file = paste0(file, ".gz"), 
          compress = TRUE, 
          width = max(c(Biostrings::width(seqs), 1))
        )
        
      }
      
    }else{
      
      ShortRead::writeFasta(
        object = seqs, 
        file = file, 
        compress = FALSE, 
        width = max(c(Biostrings::width(seqs), 1))
      )
      
    }
    
  }else{
    
    if( compress ){
      
      if( grepl(".gz$", file) ){
        
        ShortRead::writeFastq(
          object = seqs, 
          file = file, 
          compress = TRUE
        )
        
      }else{
        
        ShortRead::writeFastq(
          object = seqs, 
          file = paste0(file, ".gz"), 
          compress = TRUE
        )
        
      }
      
    }else{
      
      ShortRead::writeFastq(
        object = seqs, 
        file = file, 
        compress = FALSE
      )
      
    }
  }
}

#' Write fast(a/q) files given zero length files.
#' 
#' @usage write_null_file(
#'          file, stat = FALSE, write.random = FALSE, compress = FALSE)
#'
#' @param file character Output file name to write sequences.
#' @param stat logical If true, null output will write null stat files as well.
#' @param write.random character If FALSE (default), no random output files will 
#' be writen. If character vector, specifies the output file names to write.
#' @param compress logical Whether to gzip compress the sequence file when 
#' written or leave it uncompressed. Default is FALSE, or uncompressed.
#' @author Christopher Nobles, Ph.D.

writeNullFile <- function(file, stat = FALSE, write.random = FALSE, 
                          compress = FALSE){
  
  if( seqFileType(file) == "fasta" ){
    null_seqs <- ShortRead::ShortRead()
  }else{
    null_seqs <- ShortRead::ShortReadQ()
  }
  
  # Write empty file
  writeSeqFiles(null_seqs, file, compress = compress)
  
  # Write zero stat
  if( stat != FALSE ){
    
    sample_name <- unlist(strsplit(file, "/"))
    sample_name <- unlist(
      strsplit(sample_name[length(sample_name)], ".fa", fixed = TRUE)
    )[1]
    
    write.table(
      data.frame(
        sampleName = sample_name,
        metric = "reads",
        count = length(null_seqs)
      ),
      file = stat,
      sep = ",", 
      row.names = FALSE, 
      col.names = FALSE, 
      quote = FALSE
    )
    
  }
  
  # Write empty random sequence file
  if( write.random != FALSE ){

    null <- lapply(write.random, function(x, compress){
      
        if( seqFileType(x) == "fasta" ){
          rand_null <- ShortRead::ShortRead()
        }else{
          rand_null <- ShortRead::ShortReadQ()
        }
      
        writeSeqFiles(rand_null, file = x, compress = compress)
      
      }, 
      compress = compress
    )
    
  }
}

#' Determine output file type from input sequence file name.
#' 
#' seq_file_type(file)
#' 
#' @param file character Vector of file name(s) to get file type.
#' @author Christopher Nobles, Ph.D.

seqFileType <- function(file){
  
  file <- unlist(strsplit(file, "/"))
  file <- file[ length(file) ]
  seq_type <- stringr::str_extract(as.character(file), "fa[\\w]*")
  
  if( any(!seq_type %in% c("fa", "fasta", "fastq")) ){
    stop("Unrecognized seq file type, please choose '*.fasta' or '*.fastq'.")
  }
  
  return(
    ifelse(
      seq_type %in% c("fa", "fasta"), 
      "fasta", 
      "fastq"
    )
  )
  
}