# Run configuration
Run_Name : "simulationB"
Sample_Info : "sampleInfo/simulationB.sampleInfo.csv"
Supplemental_Info : "sampleInfo/simulationB.supp.csv"
Ref_Genome : "hg38"
Aligner : "blat"
UMItags : TRUE
Abundance_Method : "Fragment"

# Sequence files
Seq_Path : "etc/tests/DataB"
R1: "Undetermined_S0_L001_R1_001.fastq.gz"
R2: "Undetermined_S0_L001_R2_001.fastq.gz"
I1: "Undetermined_S0_L001_I1_001.fastq.gz"
I2: "Undetermined_S0_L001_I2_001.fastq.gz"

# SampleInfo formating
Sample_Name_Column : "sampleName"

# Sequence information
R1_Leading_Trim : "."
R1_Overreading_Trim : "TCGCGTATACCGTTATTAACATATGACAACTCAA"
R2_Leading_Trim : "TTGAGTTGTCATATGTTAATAACGGTAT"
R2_Leading_Trim_ODN : "ACGCGA"
R2_Overreading_Trim : "AGATCGGAAGAGCGTCGTGT"

# Target sequence information, do not include PAM sequence with gRNAs
Target_Sequences:
    B2M : "GAGTAGCGCGAGCACAGCTA"
    TRAC : "TGTGCTAGACATGAGGTCTA"
    TRBC : "GGAGAATGACGAGTGGACCC"
On_Target_Sites :
    B2M : "chr15:-:44711569"
    TRAC : "chr14:+:22547664"
    TRBC'1 : "chr7:+:142792010-142792030"
    TRBC'2 : "chr7:+:142801367"

# Specimen target treatment
# Data can be input here or referenced in sampleInfo by just putting 
# 'sampleInfo:{column}'. For simplicity, if all specimens were treated with the 
# same target sequence(s), the sample can be named 'all' followed by the treated
# target sequence name(s). If placing data in sampleInfo, delimit multiple 
# target sequence names with a semicolon ';'.
Treatment :
    all : "sampleInfo:gRNA"

# Specimen nuclease treatment
# Similar to target treatment above, this parameter dictates which nuclease(s)
# where used on the specimens. This refers to the class of nuclease, such as
# Cas9 or Cpf1, which behave differently when they edit DNA. Notation can follow
# the same as above, if all specimens were treated with the same class of 
# nuclease, then just specify 'all : "{nuclease_profile}"', or list out by 
# specimen. Additionally you can specify the column in sampleInfo in the same 
# format as above. Currently, iGUIDE does not support processing for specimens 
# with multiple classes of nuclease profiles. Only one profile can be specified
# per specimen.
Nuclease :
    all : "Cas9"
    
# Nuclease profile
# Whatever name is given to the nuclease, specify parameter below that dictate
# how the nuclease cuts DNA. 'PAM' - protospacer adjacent motif - should be 
# specified here and can contain ambiguous nucleotides. 'PAM_Loc' indicates the 
# location of the PAM with respect to the pattern, either '5p', '3p' or FALSE.
# 'PAM_Tol' indicates the tolerance for mismatches in the PAM sequence (ignorned
# if PAM is FALSE). 'Cut_Offset' indicates the offset from the 5' nucleotide of 
# the PAM sequence where the nuclease creates a double strand break, unless PAM 
# is FALSE, then the 5' position of the target sequence (also accepts 
# "mid_insert" to specify middle of region between paired alignments). 
# 'Insert_size' is used if target sequences are expected to flank each other for
# editing, such as with TALENs, and indicates the expected size of the insert. 
# To input a range, delimit the min and max by a colon, ie. 15:21. All names of 
# nucleases used to treat specimens need to have a profile. Additional profiles 
# should be added under the 'Nuclease_Profiles' parameter.
Nuclease_Profiles :
    Cas9 :
        PAM : "NGG"
        PAM_Loc : "3p"
        PAM_Tol : 1
        Cut_Offset : -4
        Insert_size : FALSE

# ------------------------------------------------------------------------------
# iGUIDE configuration
Read_Types : ["R1", "R2", "I1", "I2"]
Genomic_Reads : ["R1", "R2"]
readNamePattern : "'[\\w\\:\\-\\+]+'"

# Memory Management (in MB units)
defaultMB : 2000
demultiMB : 40000
trimMB : 8000
filtMB : 4000
consolMB : 4000
alignMB : 20000
qualCtrlMB : 16000
assimilateMB : 16000
evaluateMB : 8000
reportMB : 4000

# Demultiplexing parameters
skipDemultiplexing : FALSE
barcode1Length : 8
barcode2Length : 8
barcode1 : "I1"
barcode2 : "I2"
bc1Mismatch : 0
bc2Mismatch : 0
maxNcount : 1

# Sequence trimming
## R1 sequence
R1leadMismatch : 0
R1overMismatch : 4
R1overMaxLength : 20
## R2 sequence
R2leadMismatch : 3
R2odnMismatch : 0
R2overMismatch : 4
R2overMaxLength : 20

# Binning
bins : 3
level : 250

# Reference Alignment
BLATparams : "-tileSize=11 -stepSize=9 -minIdentity=85 -maxIntron=5 -minScore=27 -dots=1000 -out=psl -noHead"
BWAparams : "-k 30 -w 2500 -P -L 25 -a"

# Post-alignment filtering
maxAlignStart : 5
minPercentIdentity : 95
minTempLength : 30
maxTempLength : 2500

# Post-processing
refGenes :
    file : "genomes/hg38.refSeq.ext.nomodel.rds"
    symbolCol : "name2"
oncoGeneList : 
    file : "genomes/allOnco_Feb2017.tsv"
    symbolCol : "symbol"
specialGeneList : 
    file : "genomes/humanLymph.tsv"
    symbolCol : "symbol"
maxTargetMismatch : 6
upstreamDist : 100
downstreamDist : 30
pileUpMin : 3
recoverMultihits : FALSE

# Report
suppFile : TRUE
tables : FALSE
figures : TRUE
reportData : FALSE
infoGraphic : TRUE
signature : "Christopher L. Nobles, Ph.D. [Bushman Lab]"
