# This script writes / generates a short report with the stat.csv file generated
# from processing a run.
# 
# usage: 
#   Rscript write_stat_report <stat.csv> -o <output> -c <config> -f <format(html/pdf)> -t <template.path> -i <iguide_dir>
# 
# Input arguments for this script include: 
#   input stat.csv file 
#   output file name / path
#   format, either 'html' (default) or 'pdf'
#   iguide installation directory, will look for sys argument 'IGUIDE_DIR'
# 

options(stringsAsFactors = FALSE, scipen = 99, width = 120)

# Set up and gather command line arguments ----
parser <- argparse::ArgumentParser(
  description = "Generate an iGUIDE Stat report for core and eval data.",
  usage = paste(
    "Rscript generate_stat_report.R <core.stat> <eval.stat> -o <output>",
    "-c <config> [-h/--help, -v/--version] [optional args]"
  )
)

parser$add_argument(
  "-r", "--core", nargs = 1, type = "character",
  help = paste(
    "Core stat object generated by iGUIDE run command. Requires csv format."
  )
)

parser$add_argument(
  "-e", "--eval", nargs = 1, type = "character",
  help = paste(
    "Eval stat object generated by iGUIDE run command. Requires csv format."
  )
)

parser$add_argument(
  "-i", "--incorpSites", nargs = 1, type = "character", required = TRUE,
  help = "Unique sites csv file from project directory."
)

parser$add_argument(
  "-o", "--output", nargs = 1, type = "character", required = TRUE,
  help = "Output report file, extension not required."
)

parser$add_argument(
  "-c", "--config", nargs = 1, type = "character", required = TRUE,
  help = "Run specific config file in yaml format."
)

parser$add_argument(
  "-f", "--format", nargs = 1, type = "character", default = "html",
  help = "Output format for report. Either 'pdf' or 'html' (default)."
)

parser$add_argument(
  "-t", "--template", nargs = 1, type = "character", 
  default = "tools/rscripts/report_templates/iGUIDE_stat_template.Rmd",
  help = "File path to standard or custom stat report template."
)

parser$add_argument(
  "--iguide_dir", nargs = 1, type = "character", default = "IGUIDE_DIR",
  help = "iGUIDE install directory path, do not change for normal applications."
)


args <- parser$parse_args(commandArgs(trailingOnly = TRUE))


if( !dir.exists(args$iguide_dir) ){
  root_dir <- Sys.getenv(args$iguide_dir)
}else{
  root_dir <- args$iguide_dir
}

if( !dir.exists(root_dir) ){
  stop(paste0("\n  Cannot find install path to iGUIDE: ", root_dir, ".\n"))
}else{
  args$iguide_dir <- root_dir
}

code_dir <- dirname(sub(
  pattern = "--file=", 
  replacement = "", 
  x = grep("--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
))

# Check input file ----
core_file <- args$core
eval_file <- args$eval
sites_file <- args$incorpSites

if(
  !file.exists(core_file) | !file.exists(eval_file) | !file.exists(sites_file)
  ){
  stop("\n  Cannot find input stat files. Check inputs.")
}

if( file.exists(args$output) ){
  cat("Removing existing output file of the same name: ", args$output, "\n")
  unlink(args$output)
}


# Check config input ----
if( !file.exists(args$config) ){
  stop("\n  Cannot find config file: ", args$config, ".\n")
}

config <- yaml::yaml.load_file(args$config)

# Check config for defaults ----
if( !"UMItags" %in% names(config) ) config$UMItags <- TRUE

if( !"Alternate_UMI_Method" %in% names(config) ){
  config$Alternate_UMI_Method <- FALSE
}

# Check for format ----
report_formats <- c("html" = "html_document", "pdf" = "pdf_document")

if( !tolower(args$format) %in% names(report_formats) ){
  stop(
    "\n  Please input either 'html' or 'pdf' for format.\n",
    "  Other formats not supported."
  )
}

output_format <- report_formats[tolower(args$format)]

# Check for template path ----
if( file.exists(file.path(root_dir, args$template)) ){
  
  template_path <- normalizePath(file.path(root_dir, args$template))
  
}else if( file.exists(file.path(args$template)) ){
  
  template_path <- normalizePath(file.path(args$template))
  
}else{
  
  stop("\n  Cannot find template file: ", args$template, ".\n")
  
}


# Load required r-packages ----
packs_loaded <- sapply(
  c("magrittr", "knitr"), require, character.only = TRUE
)

if( !any(packs_loaded) ){
  stop(
    "\n  Could not find required r-package: ", 
    paste(names(packs_loaded)[packs_loaded], collapse = ", "), 
    ".\n"
  )
}


# Get versioning ----
soft_version <- as.character(read.delim(
  file = file.path(root_dir, ".version"), header = FALSE
))

build_version <- list.files(file.path(root_dir, "etc")) %>%
  grep(pattern = "build.b[0-9\\.]+.*", x = ., value = TRUE) %>%
  stringr::str_extract(pattern = "b[0-9]+\\.[0-9]+\\.[0-9]+")

signature <- config[["signature"]]

# Load input data ----
core_stat_df <- read.csv(core_file) %>%
  dplyr::select(
    -align.unique.reads, -align.unique.algns, -align.unique.loci
  )

eval_stat_df <- read.csv(eval_file)

site_stat_df <- readRDS(sites_file)$reads %>%
  dplyr::filter(type == "uniq") %>%
  dplyr::group_by(sampleName) %>%
  dplyr::summarise(
    align.unique.reads = dplyr::n_distinct(ID),
    align.unique.algns = dplyr::n_distinct(seqnames, start, end, strand),
    align.unique.loci = dplyr::n_distinct(
      seqnames, strand, ifelse(strand == "+", start, end)
    )
  )

stat_df <- dplyr::full_join(core_stat_df, eval_stat_df, by = "sampleName") %>%
  dplyr::full_join(site_stat_df, by = "sampleName") %>%
  dplyr::mutate_all(function(x) ifelse(is.na(x), rep(0, length(x)), x))

sampleName_levels <- unique(stat_df$sampleName)

if( 
  any(c("ambiguous_reads", "degenerate_reads", "unassigned_reads") %in% 
      sampleName_levels) 
  ){
  
    sampleNames <- sampleName_levels[
      -match(
        c("ambiguous_reads", "degenerate_reads", "unassigned_reads"), 
        sampleName_levels
      )
    ]
    
}else{
  
  sampleNames <- sampleName_levels
  
}

sampleName_levels <- c(
  sampleNames, "ambiguous_reads", "degenerate_reads", "unassigned_reads"
)


# Read attrition table ----
read_tbl <- dplyr::select(
    stat_df, c(
      "sampleName", "demulti.reads", 
      "R1.trim.reads", 
      if( config$Alternate_UMI_Method ) "R1.primer.trim.reads",
      if( !config$Alternate_UMI_Method ) "R2.primer.trim.reads",
      "R2.trim.reads", 
      if( config$UMItags ) "umitags.reads", 
      "filt.reads", 
      if( tolower(config$Aligner) == "blat" ) "R1.consol.reads", 
      if( tolower(config$Aligner) == "blat" ) "R2.consol.reads", 
      "align.unique.reads", 
      "align.chimera.reads", 
      "align.multihit.reads"
  )) %>%
  dplyr::mutate(sampleName = factor(sampleName, levels = sampleName_levels)) %>%
  dplyr::arrange(sampleName)

names(read_tbl) <- stringr::str_replace(names(read_tbl), ".reads$", "")


# Alignment outcome table ----
algn_tbl <- dplyr::select(
    stat_df, sampleName, align.unique.reads, align.unique.algns, 
    align.unique.loci, align.multihit.reads, align.multihit.lengths, 
    align.multihit.clusters, align.chimera.reads
  ) %>%
  dplyr::filter(sampleName %in% sampleNames) %>%
  dplyr::mutate(sampleName = factor(sampleName, levels = sampleNames)) %>%
  dplyr::arrange(sampleName)

names(algn_tbl) <- stringr::str_replace(names(algn_tbl), "align.", "")


# Incorporation breakdown table ----
incorp_levels <- c(
  "eval.total.algns", "eval.combined.algns", 
  "eval.pileup.algns", "eval.paired.algns", "eval.matched.algns", 
  "eval.ontarget.algns", "eval.offtarget.algns"
)

incorp_tbl <- stat_df[, names(stat_df) %in% c("sampleName", incorp_levels)] %>%
  tidyr::gather(key = "metric", value = "counts", -sampleName) %>%
  dplyr::mutate(metric = factor(metric, levels = incorp_levels)) %>%
  tidyr::complete(metric) %>%
  dplyr::mutate(metric = as.character(metric)) %>%
  tidyr::spread(key = metric, value = counts) %>%
  dplyr::select(
    sampleName, eval.total.algns, eval.combined.algns, 
    eval.pileup.algns, eval.paired.algns, eval.matched.algns, 
    eval.ontarget.algns, eval.offtarget.algns
  ) %>%
  dplyr::filter(sampleName %in% sampleNames) %>%
  dplyr::mutate(sampleName = factor(sampleName, levels = sampleNames)) %>%
  dplyr::arrange(sampleName)

names(incorp_tbl) <- stringr::str_replace(names(incorp_tbl), "eval.", "")
names(incorp_tbl) <- stringr::str_replace(names(incorp_tbl), ".algns$", "")


# Initiate report generation ----
# Normalize file output path
write(c(), file = args$output)
output_file <- normalizePath(args$output)
unlink(output_file)

output_path <- unlist(strsplit(output_file, "/"))
output_dir <- paste(output_path[seq_len(length(output_path)-1)], collapse = "/")
output_file <- output_path[length(output_path)]

if( output_format == "html_document" & !stringr::str_detect(output_file, ".html$") ){
  output_file <- paste0(output_file, ".html")
}

if( output_format == "pdf_document" & !stringr::str_detect(output_file, ".pdf$") ){
  output_file <- paste0(output_file, ".pdf")
}

if( output_format == "html_document" ){
  
  css_path <- normalizePath(file.path(code_dir, "report_templates/iguide.css"))
  
  rmarkdown::render(
    input = template_path,
    output_format = output_format, 
    output_file = output_file,
    output_dir = output_dir,
    output_options = list("css" = css_path)
  )
  
}else{
  
  rmarkdown::render(
    input = template_path,
    output_format = output_format, 
    output_file = output_file,
    output_dir = output_dir
  )
  
}

q()
